name: Auto Review

on:
  pull_request:
    branches-ignore:
      - main
    types:
      - opened

jobs:
  AutoReview:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: 🔄 Checkout to the branch
        uses: actions/checkout@v4

      - name: 🤖 Auto Review
        uses: akiojin/auto-review-github-action@v2
        continue-on-error: true
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          target: 'ts,yml,md'
          language: 日本語
